- name: Install nginx 
  apt: pkg=nginx state=installed update_cache=yes

- name: Create/sync the site configuration
  template: src=$nginx_vhost_template dest=/etc/nginx/sites-available/$nginx_site mode=0755

- name: ensure default Nginx site is not enabled
  file: state=absent path=/etc/nginx/sites-enabled/default

- name: Enable the site 
  file: state=link src=/etc/nginx/sites-available/$nginx_site path=/etc/nginx/sites-enabled/$nginx_site

- name: restart nginx 
  service: name=nginx state=started

